### ISSUE TITLE
Source maps are not working

### ISSUE THREAD

**Issue by grahamcarlyle** [awslabs/amazon-quicksight-embedding-sdk#143]
Source maps are not working as the hosting domain is not resolving

In chrome:
`DevTools failed to load source map: Could not load content for https://sourcemaps.prod.us-east-1.quicksight.aws.a2z.com/charting/1.0.13932.0/esm/252.bundle.f40e4d4f02a96d99.2.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED `

**Comment by bwelkin** [comment]
If the issue is still present, could you provide repro steps.

**Comment by grahamcarlyle** [comment]
When I create either a development or production build of our app (using shadow-cljs) I get runtime warnings in the chrome devtools console of the chrome browser complaining about not being able to resolve the source map domain for the awsk qs sdk code

Heres an image of the message I included in the issue description in situ..
![image](https://user-images.githubusercontent.com/683360/230053374-e0330aaf-d7d4-4613-83db-253a56d1cec2.png)

**Comment by jonathanRinciari** [comment]
Updating to the latest version should resolve this issue. If that is not the case please reopen. Thanks

**Comment by grahamcarlyle** [comment]
This issue is not resolved for me, using the latest version i can see (amazon-quicksight-embedding-sdk 2.5.0)

Still seems to be the same issue of the source map hosting domain not resolving

![image](https://github.com/awslabs/amazon-quicksight-embedding-sdk/assets/683360/07edca9e-36ac-422f-9850-dd4b5b934f37)

**Comment by brianwyka** [comment]
I'm getting the error as well with `2.6.0`
